extends: markdownlint/style/relaxed
$schema: https://raw.githubusercontent.com/DavidAnson/markdownlint/v0.34.0/schema/markdownlint-config-schema.json
default: true
whitespace: true
MD013:
  line_length: 80
  code_blocks: false
  tables: false
